// ============================================================================
// Project : Renewable Energy Plant System (REPS)
// File    : alerts/AlertSystem.scala
// Authors : Mahi, Oyshe, Nguyen
// Description: Functional alert/issue detection system for the plant.
//              Detects anomalies such as low energy output, equipment
//              malfunctions, and generates alerts for operators.
//
// FP concepts demonstrated:
//   - Recursion: consecutive-zero detection uses tail-recursive helper
//   - Higher-order functions: map, filter used for alert generation
//   - Pattern matching: severity classification, alert formatting
//   - ADT error handling: RepsResult[A] used for input validation
//   - Immutability: all functions return new lists; no mutation
// ============================================================================

package alerts

import models.{EnergyReading, EnergySource}
import utils.{RepsResult, Success, Failure}

/**
 * Severity levels for alerts generated by the system.
 */
enum AlertSeverity:
  case Info
  case Warning
  case Critical

/**
 * Immutable representation of a plant alert.
 *
 * @param source   the energy source that triggered the alert
 * @param severity the severity level of the alert
 * @param message  a human-readable description of the issue
 * @param reading  the specific reading that caused the alert (if applicable)
 */
case class Alert(
  source: EnergySource,
  severity: AlertSeverity,
  message: String,
  reading: Option[EnergyReading] = None
)

/**
 * Object containing functions for detecting issues and generating alerts.
 *
 * From the project specification (Use Case 5):
 *   - Detect low energy output.
 *   - Detect equipment malfunction.
 *   - Generate alerts for operators.
 */
object AlertSystem:

  // ---------------------------------------------------------------------------
  // UC5 — Issue detection
  // ---------------------------------------------------------------------------

  /**
   * Analyzes a list of readings and generates alerts for any detected issues.
   *
   * Detection rules:
   *   1. **Low output** — a reading with energyMW below `lowThreshold`.
   *      - Below threshold but > 0  → Warning
   *      - Exactly 0                → Critical (possible outage)
   *   2. **Equipment malfunction** — 3 or more consecutive zero readings
   *      from the same source, which likely indicates a sensor or equipment
   *      failure rather than naturally low production.
   *
   * Uses RepsResult for input validation: if the readings list is empty,
   * the function wraps the result in a Failure internally but still returns
   * a safe empty list (demonstrating functional error handling).
   *
   * Demonstrates: higher-order functions (map, filter), pattern matching,
   *               recursion (consecutive-zero detection), RepsResult usage.
   *
   * @param readings       the list of energy readings to analyze
   * @param lowThreshold   the MW threshold below which a "low output" alert is generated
   * @return a list of Alert objects (may be empty if no issues are found)
   */
  def detectIssues(readings: List[EnergyReading], lowThreshold: Double = 10.0): List[Alert] =
    // Validate input using RepsResult — empty data is not an error per se,
    // but we handle it gracefully through our ADT.
    val validated: RepsResult[List[EnergyReading]] =
      RepsResult.attempt {
        if readings.isEmpty then
          throw new IllegalArgumentException("No readings provided for alert detection")
        else
          readings
      }

    validated match
      case Failure(_) => Nil  // No data → no alerts
      case Success(data) =>
        val lowOutputAlerts       = detectLowOutput(data, lowThreshold)
        val malfunctionAlerts     = detectEquipmentMalfunction(data)
        // Combine and deduplicate: malfunction alerts take priority over
        // individual low-output alerts for the same reading window
        lowOutputAlerts ++ malfunctionAlerts

  // ---------------------------------------------------------------------------
  // Low energy output detection
  // ---------------------------------------------------------------------------

  /**
   * Detects readings where energy output is below the configured threshold.
   * Assigns severity based on the reading value:
   *   - energyMW == 0  → Critical (possible outage)
   *   - energyMW < lowThreshold → Warning (underperforming)
   *
   * Demonstrates: higher-order functions (filter, map), pattern matching.
   *
   * @param readings     the readings to check
   * @param lowThreshold the MW threshold
   * @return a list of low-output alerts
   */
  private def detectLowOutput(readings: List[EnergyReading], lowThreshold: Double): List[Alert] =
    readings
      .filter(_.energyMW < lowThreshold)
      .map { reading =>
        val severity = reading.energyMW match
          case mw if mw <= 0.0 => AlertSeverity.Critical
          case mw if mw < lowThreshold * 0.5 => AlertSeverity.Warning
          case _ => AlertSeverity.Info

        val message = reading.energyMW match
          case mw if mw <= 0.0 =>
            f"Zero energy output detected at ${reading.startTime}. Possible outage or sensor failure."
          case mw =>
            f"Low energy output: $mw%.2f MW (threshold: $lowThreshold%.2f MW) at ${reading.startTime}."

        Alert(
          source   = reading.source,
          severity = severity,
          message  = message,
          reading  = Some(reading)
        )
      }

  // ---------------------------------------------------------------------------
  // Equipment malfunction detection (consecutive zero readings)
  // ---------------------------------------------------------------------------

  /**
   * Detects equipment malfunctions by finding sequences of 3 or more
   * consecutive zero readings from the same energy source.
   *
   * The readings are first grouped by source, then each group is scanned
   * using a tail-recursive helper to find consecutive-zero runs.
   *
   * Demonstrates: recursion (tail-recursive scan), pattern matching,
   *               higher-order functions (groupBy, flatMap).
   *
   * @param readings the readings to analyze
   * @return a list of malfunction alerts (one per detected sequence)
   */
  private def detectEquipmentMalfunction(readings: List[EnergyReading]): List[Alert] =
    // Minimum consecutive zero readings to trigger a malfunction alert
    val consecutiveZeroThreshold = 3

    // Group readings by source so we check each source independently
    val bySource: Map[EnergySource, List[EnergyReading]] =
      groupBySource(readings)

    // For each source, find runs of consecutive zeros
    bySource.toList.flatMap { case (source, sourceReadings) =>
      // Sort by time to ensure correct ordering for consecutive detection
      val sorted = sourceReadings.sortBy(_.startTime)
      val runs   = findConsecutiveZeroRuns(sorted, consecutiveZeroThreshold)

      runs.map { run =>
        Alert(
          source   = source,
          severity = AlertSeverity.Critical,
          message  = s"Equipment malfunction suspected: ${run.size} consecutive zero readings " +
                     s"detected from ${run.head.startTime} to ${run.last.endTime}.",
          reading  = Some(run.head)  // Reference the first reading in the run
        )
      }
    }

  /**
   * Groups readings by their energy source.
   * Implemented recursively to demonstrate FP principles.
   *
   * @param readings the readings to group
   * @return a map from EnergySource to list of readings
   */
  private def groupBySource(readings: List[EnergyReading]): Map[EnergySource, List[EnergyReading]] =
    // Tail-recursive accumulation
    @scala.annotation.tailrec
    def go(remaining: List[EnergyReading], acc: Map[EnergySource, List[EnergyReading]]): Map[EnergySource, List[EnergyReading]] =
      remaining match
        case Nil => acc.map { case (k, v) => (k, v.reverse) }
        case head :: tail =>
          val updated = acc.updatedWith(head.source) {
            case Some(existing) => Some(head :: existing)
            case None           => Some(List(head))
          }
          go(tail, updated)

    go(readings, Map.empty)

  /**
   * Finds all runs of consecutive zero readings that meet or exceed
   * the minimum length threshold.
   *
   * Uses a tail-recursive helper to scan through the sorted list,
   * accumulating the current run and collecting completed runs.
   *
   * Demonstrates: tail recursion, pattern matching on lists.
   *
   * @param sortedReadings readings sorted by time
   * @param minRunLength   minimum consecutive zeros to flag
   * @return a list of runs (each run is a list of consecutive zero readings)
   */
  private def findConsecutiveZeroRuns(
    sortedReadings: List[EnergyReading],
    minRunLength: Int
  ): List[List[EnergyReading]] =

    @scala.annotation.tailrec
    def go(
      remaining: List[EnergyReading],
      currentRun: List[EnergyReading],
      completedRuns: List[List[EnergyReading]]
    ): List[List[EnergyReading]] =
      remaining match
        case Nil =>
          // End of list — check if the current run qualifies
          if currentRun.size >= minRunLength then
            (currentRun.reverse :: completedRuns).reverse
          else
            completedRuns.reverse

        case head :: tail =>
          if head.energyMW == 0.0 then
            // Continue building the current zero-run
            go(tail, head :: currentRun, completedRuns)
          else
            // Non-zero reading breaks the run
            if currentRun.size >= minRunLength then
              go(tail, Nil, currentRun.reverse :: completedRuns)
            else
              go(tail, Nil, completedRuns)

    go(sortedReadings, Nil, Nil)

  // ---------------------------------------------------------------------------
  // Alert formatting
  // ---------------------------------------------------------------------------

  /**
   * Formats a list of alerts into human-readable strings for display
   * to plant operators. Each alert is formatted with a severity indicator,
   * source label, and descriptive message.
   *
   * Uses RepsResult to handle the case where the alert list might be empty,
   * providing a meaningful default message.
   *
   * Demonstrates: pattern matching, higher-order functions (map),
   *               RepsResult usage.
   *
   * @param alerts the alerts to format
   * @return a list of formatted alert strings
   */
  def formatAlerts(alerts: List[Alert]): List[String] =
    // Validate using RepsResult — provide a helpful message if no alerts
    val validated: RepsResult[List[Alert]] =
      if alerts.isEmpty then Failure("No alerts to display")
      else Success(alerts)

    validated match
      case Failure(msg) => List(s"[OK] $msg - all systems nominal.")
      case Success(alertList) =>
        alertList.map { alert =>
          val severityIcon = alert.severity match
            case AlertSeverity.Info     => "[INFO]    "
            case AlertSeverity.Warning  => "[WARNING] "
            case AlertSeverity.Critical => "[CRITICAL]"

          val timeInfo = alert.reading match
            case Some(r) => s" | Time: ${r.startTime}"
            case None    => ""

          s"$severityIcon | ${alert.source}$timeInfo - ${alert.message}"
        }
