// ============================================================================
// Project : Renewable Energy Plant System (REPS)
// File    : alerts/AlertSystem.scala
// Authors : Mahi, Oyshe, Nguyen
// Description: Functional alert/issue detection system for the plant.
//              Detects anomalies such as low energy output, equipment
//              malfunctions, and generates alerts for operators.
// ============================================================================

package alerts

import models.{EnergyReading, EnergySource}

/**
 * Severity levels for alerts generated by the system.
 */
enum AlertSeverity:
  case Info
  case Warning
  case Critical

/**
 * Immutable representation of a plant alert.
 *
 * @param source   the energy source that triggered the alert
 * @param severity the severity level of the alert
 * @param message  a human-readable description of the issue
 * @param reading  the specific reading that caused the alert (if applicable)
 */
case class Alert(
  source: EnergySource,
  severity: AlertSeverity,
  message: String,
  reading: Option[EnergyReading] = None
)

/**
 * Object containing functions for detecting issues and generating alerts.
 *
 * From the project specification (Use Case 5):
 *   - Detect low energy output.
 *   - Detect equipment malfunction.
 *   - Generate alerts for operators.
 */
object AlertSystem:

  /**
   * Analyzes a list of readings and generates alerts for any detected issues.
   *
   * @param readings       the list of energy readings to analyze
   * @param lowThreshold   the MW threshold below which a "low output" alert is generated
   * @return a list of Alert objects (may be empty if no issues are found)
   */
  def detectIssues(readings: List[EnergyReading], lowThreshold: Double = 10.0): List[Alert] =
    // TODO: Nguyen — implement issue detection logic
    //   Suggestions:
    //   - Flag readings with energyMW below lowThreshold
    //   - Flag consecutive zero readings as potential equipment malfunction
    //   - Use pattern matching and higher-order functions
    Nil

  /**
   * Formats a list of alerts into human-readable strings for display.
   *
   * @param alerts the alerts to format
   * @return a list of formatted alert strings
   */
  def formatAlerts(alerts: List[Alert]): List[String] =
    // TODO: Nguyen — implement
    alerts.map(a => s"[${a.severity}] ${a.source}: ${a.message}")
